-- Run this in your Supabase SQL Editor

DROP TABLE IF EXISTS public.submissions;
DROP TABLE IF EXISTS public.question_hints;
DROP TABLE IF EXISTS public.question_templates;
DROP TABLE IF EXISTS public.round_config;
DROP TABLE IF EXISTS public.q11_sets;
DROP TABLE IF EXISTS public.teams;

-- 1. q11_sets Table
CREATE TABLE public.q11_sets (
  id INT PRIMARY KEY,
  set_name TEXT NOT NULL,
  question_text TEXT NOT NULL,
  codeword TEXT NOT NULL
);
ALTER TABLE public.q11_sets ENABLE ROW LEVEL SECURITY;

-- 2. Teams Table
-- The 'id' now maps directly to the UUID generated by Supabase Auth (auth.users)
CREATE TABLE public.teams (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    team_id TEXT UNIQUE NOT NULL,
    team_name TEXT NOT NULL,
    pass TEXT NOT NULL,
    instance_id TEXT NOT NULL,
    q11_set_id INT REFERENCES public.q11_sets(id),
    correct_code TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;

-- 3. Round Config Table (Only ever needs one row)
CREATE TABLE public.round_config (
    id INT PRIMARY KEY DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'CLOSED', -- 'ACTIVE' or 'CLOSED'
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    max_qualifiers INT NOT NULL DEFAULT 20
);
ALTER TABLE public.round_config ENABLE ROW LEVEL SECURITY;

-- 3. Question Templates Table
CREATE TABLE public.question_templates (
    id TEXT PRIMARY KEY,
    question_text TEXT NOT NULL,
    formula TEXT NOT NULL,
    hint TEXT
);
ALTER TABLE public.question_templates ENABLE ROW LEVEL SECURITY;

-- 4. Question Hints Table
CREATE TABLE public.question_hints (
    question_id TEXT PRIMARY KEY REFERENCES public.question_templates(id) ON DELETE CASCADE,
    enabled BOOLEAN NOT NULL DEFAULT false
);
ALTER TABLE public.question_hints ENABLE ROW LEVEL SECURITY;

-- 5. Submissions Table
CREATE TABLE public.submissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id TEXT NOT NULL REFERENCES public.teams(team_id) ON DELETE CASCADE,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    rank INT NOT NULL,
    status TEXT NOT NULL, -- 'QUALIFIED' or 'COMPLETED_NOT_QUALIFIED'
    CONSTRAINT unique_team_submission UNIQUE(team_id)
);
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

-- Note: RLS is explicitly ENABLED for all tables above to prevent direct 
-- client-side access via the anon key. 
-- Our Node.js backend uses the SUPABASE_SERVICE_ROLE_KEY which automatically 
-- bypasses RLS, acting as a secure intermediary.
